// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package opendistro

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "opendistro", asset.ModuleFieldsPri, AssetOpendistro); err != nil {
		panic(err)
	}
}

// AssetOpendistro returns asset data.
// This is the base64 encoded zlib format compressed contents of module/opendistro.
func AssetOpendistro() string {
	return "eJzElUFuszAQhfecYpR9OACLf/dLTaVm2W1l8JC4sT2WPaTh9hUhpNR1AqpSMUtGfu99M8JewwHbAsihlSqwpwyAFWssYPX1cZUBeNQoAhZQIosMQGKovHKsyBbwLwOAkQoYko3GDKBWqGUozv01WGEwcuuKW4cF7Dw17vIlof5da6xX6SYw+rfAgsO1m5LtKgYZKmnZ1y2DONA4FJ6EcecRjKuPdMD2g7yMencCdPW/F+xNf8zAksRJ9DsO0fnrkHZiJu8RfVBkH8e7JYmDap60fD+apF2MPcPs+fUFNramPOqkiKepp8hnBBpCJQcwTmDQkG/zPQqXK6s4L1vGcDOQJrtLNGvyRnABtw7PSPuEwkGXAJqAEsoWeI9nBmV73XkQRpyWZTDi9HsES3b5VWzJrh+wjoFlyY1cUeZvZaBwnioMITeaqoPQOnlXlEQaRfwDTwTb1IM4dNoouySXoSVv5r97mpLqC75LnwEAAP//+TgUsQ=="
}
