// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package shell

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "shell", asset.ModuleFieldsPri, AssetShell); err != nil {
		panic(err)
	}
}

// AssetShell returns asset data.
// This is the base64 encoded zlib format compressed contents of module/shell.
func AssetShell() string {
	return "eJx8j00OwiAQhfec4qX7XoCFOw+C5amkQyFAo729afGn1sZvx0z43psWPSeNfKWIAoorQo1meTcKSBSaTI0Ti1GAZe6Si8WFQeOgANS/8MGOQgWcHcVmvaxaDMbzo58pU6TGJYUxPic7zm/NWtUF781g3/M94cy2+IvdsMqveltiXYR34+Ny8Zpapud0C8ludn+iZ45VWEPVIwAA///sc2wV"
}
